version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TFSEC_VERSION: "v1.28.11"


phases:
  install:
    runtime-versions:
      python: 3.12
      golang: 1.21
    commands:
      - echo Updating OS 
      - yum update -y --quiet
      - echo Installing jq, awscli, pip3, go, tflint, tfsec, checkov
      - yum install -y jq awscli --quiet
      - pip3 install checkov --quiet
      - yum install -y golang --quiet
      - wget -q -O tfsec https://github.com/aquasecurity/tfsec/releases/download/${TFSEC_VERSION}/tfsec-linux-amd64
      - chmod +x ./tfsec
      - mv ./tfsec /usr/local/bin/tfsec
      - curl -s https://raw.githubusercontent.com/terraform-linters/tflint/master/install_linux.sh | bash
      - cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}
      - echo Copying .tflint.hcl configuration file if not already present
      - if [ ! -f ".tflint.hcl" ]; then cp .tflint.hcl ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}/; fi
  pre_build:
    commands:
  build:
    commands:
      - echo Running tflint
      - tflint --init
      - tflint --chdir=./terraform --recursive
      - echo Running tfsec
      - tfsec . -m MEDIUM
      - echo Running checkov
      - checkov --framework terraform -d ./
