version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TF_VERSION: "1.9.7"


phases:
  install:
    runtime-versions:
      python: 3.12
      golang: 1.21
    commands:
      - echo Installing Terraform    
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - rm -f /bin/terraform # Remove any existing Terraform binary to avoid conflicts
      - mkdir -p tmp_terraform && unzip -o terraform.zip -d tmp_terraform # Unzip to a temporary directory
      - mv tmp_terraform/terraform /bin # Move binary to /bin
      - rm -rf tmp_terraform terraform.zip # Clean up temporary files
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}
      - pwd
      - ls -lahR
      - echo Running Terraform init
      - terraform init
      - echo Formatting Terraform code
      - terraform fmt -recursive
      - echo Validating Terraform code
      - terraform validate
