version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TF_VERSION: "1.9.7"


phases:
  install:
    commands:
      - echo Installing Terraform    
      - curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip
      - rm -f /bin/terraform # Remove any existing Terraform binary to avoid conflicts
      - mkdir -p tmp_terraform && unzip -o terraform.zip -d tmp_terraform # Unzip to a temporary directory
      - mv tmp_terraform/terraform /bin # Move binary to /bin
      - rm -rf tmp_terraform terraform.zip # Clean up temporary files
  pre_build:
    commands:
  build:
    commands:
      - cd ${CODEBUILD_SRC_DIR}/${CODE_SRC_DIR}
      - echo Running Terraform init
      - terraform init
      - echo Running Terraform Plan
      - terraform plan -out tfapply
artifacts:
  files:
    - '**/*'
