version: 0.2

env:
  variables:
    CODE_SRC_DIR: "."
    TF_VERSION: "1.9.7"

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - "curl -s -qL -o terraform.zip https://releases.hashicorp.com/terraform/${TF_VERSION}/terraform_${TF_VERSION}_linux_amd64.zip"
      - "unzip -o terraform.zip"
      - "mv terraform /bin"
      - "rm terraform.zip"
  build:
    commands: 
      - "echo ## Displaying the TFPlan folder structure"
      - "ls -R ${CODEBUILD_SRC_DIR}/TFPlan" # This will show the folder with the random hash
      - "TFPLAN_DIR=$(find ${CODEBUILD_SRC_DIR}/TFPlan -type f -name 'tfapply' | xargs dirname)" # Find the directory containing 'tfapply'
      - "echo Contents of TFPLAN_DIR"
      - "ls -R ${TFPLAN_DIR}"      
      - "echo ## Applying Terraform plan from $TFPLAN_DIR"
      - "terraform apply -input=false $TFPLAN_DIR/tfapply" # Use the correct path dynamically

artifacts:
  files:
    - '**/*'